name: Build, Test, Deploy, and Run on EC2

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
env:
  Version: 1.0.0
  DB_URL: ${{secrets.DB_URL}}
  DB_USERNAME : ${{secrets.DB_USERNAME}}
  DB_PASSWORD : ${{secrets.DB_PASSWORD}}

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar
          path: target/Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar

      - name: Run Tests
        id: test
        run: mvn test

  Deploy-And-Run:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar
          path: target

      - name: Remove previous JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script_stop: true
          script: |
            PID=$(sudo lsof -t -i:8080)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi
            rm -f /home/ec2-user/Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script_stop: true
          source: 'target/Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar'
          target: '/home/ec2-user/'

      - name: Run Spring Boot on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script_stop: true
          envs: DB_URL,DB_USERNAME,DB_PASSWORD
          script: |
            cd /home/ec2-user/target
            export DB_URL=$DB_URL
            export DB_USERNAME=$DB_USERNAME
            export DB_PASSWORD=$DB_PASSWORD
            nohup java -jar Hybrid-Haven-API-${{env.Version}}-SNAPSHOT.jar > output.log 2>&1 &